// Seed data for development and testing
export const sampleProviders = [
  {
    id: '1',
    name: 'SunPower Solutions',
    businessName: 'SunPower Solutions LLC',
    location: 'California, USA',
    address: '123 Solar Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    phone: '(555) 123-4567',
    email: 'contact@sunpowersolutions.com',
    website: 'https://sunpowersolutions.com',
    licenseNumber: 'CA-987654',
    yearsInBusiness: 15,
    employeeCount: 50,
    serviceArea: 'Northern California',
    specialties: ['Residential Solar', 'Commercial Solar', 'Battery Storage'],
    brandsWorkedWith: ['Tesla', 'SunPower', 'LG', 'Enphase'],
    averageCostPerWatt: '3.50',
    averageTurnaroundDays: 45,
    overallRating: '4.8',
    totalReviews: 127,
    totalLeads: 45,
    isVerified: true,
    isActive: true,
    verificationDate: '2023-01-15',
    createdAt: '2022-01-01',
    updatedAt: '2024-01-15'
  },
  {
    id: '2',
    name: 'Green Energy Experts',
    businessName: 'Green Energy Experts Inc',
    location: 'Texas, USA',
    address: '456 Renewable Ave',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    phone: '(555) 987-6543',
    email: 'info@greenenergyexperts.com',
    website: 'https://greenenergyexperts.com',
    licenseNumber: 'TX-123456',
    yearsInBusiness: 8,
    employeeCount: 25,
    serviceArea: 'Central Texas',
    specialties: ['Residential Solar', 'Solar Maintenance', 'Energy Audits'],
    brandsWorkedWith: ['Canadian Solar', 'Trina Solar', 'SolarEdge'],
    averageCostPerWatt: '3.25',
    averageTurnaroundDays: 30,
    overallRating: '4.6',
    totalReviews: 89,
    totalLeads: 32,
    isVerified: true,
    isActive: true,
    verificationDate: '2023-03-20',
    createdAt: '2022-06-01',
    updatedAt: '2024-01-10'
  },
  {
    id: '3',
    name: 'Solar City Pros',
    businessName: 'Solar City Professionals',
    location: 'Florida, USA',
    address: '789 Sunshine Blvd',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    phone: '(555) 456-7890',
    email: 'hello@solarcitypros.com',
    website: 'https://solarcitypros.com',
    licenseNumber: 'FL-789012',
    yearsInBusiness: 12,
    employeeCount: 35,
    serviceArea: 'South Florida',
    specialties: ['Commercial Solar', 'Industrial Solar', 'Solar Financing'],
    brandsWorkedWith: ['First Solar', 'Jinko Solar', 'Fronius'],
    averageCostPerWatt: '3.75',
    averageTurnaroundDays: 60,
    overallRating: '4.4',
    totalReviews: 156,
    totalLeads: 67,
    isVerified: false,
    isActive: true,
    verificationDate: null,
    createdAt: '2021-09-01',
    updatedAt: '2024-01-05'
  }
]

export const sampleReviews = [
  {
    id: '1',
    providerId: '1',
    userId: 'user_1',
    rating: 5,
    title: 'Excellent service and installation',
    content: 'SunPower Solutions did an amazing job installing our 8kW system. The team was professional, punctual, and cleaned up after themselves. Our electric bill has dropped by 90%!',
    projectType: 'residential',
    systemSize: '8.0',
    totalCost: '24000.00',
    costPerWatt: '3.00',
    installationDate: '2023-11-15',
    communicationRating: 5,
    timelinessRating: 5,
    qualityRating: 5,
    valueRating: 4,
    isVerified: true,
    isPublished: true,
    createdAt: '2023-12-01',
    updatedAt: '2023-12-01'
  },
  {
    id: '2',
    providerId: '1',
    userId: 'user_2',
    rating: 4,
    title: 'Great experience overall',
    content: 'Very happy with the installation. The only minor issue was a slight delay due to permit processing, but the team kept us informed throughout.',
    projectType: 'residential',
    systemSize: '6.5',
    totalCost: '19500.00',
    costPerWatt: '3.00',
    installationDate: '2023-10-20',
    communicationRating: 4,
    timelinessRating: 3,
    qualityRating: 5,
    valueRating: 4,
    isVerified: true,
    isPublished: true,
    createdAt: '2023-11-05',
    updatedAt: '2023-11-05'
  },
  {
    id: '3',
    providerId: '2',
    userId: 'user_3',
    rating: 5,
    title: 'Outstanding customer service',
    content: 'Green Energy Experts went above and beyond. They helped us navigate the rebate process and even assisted with financing options. Highly recommend!',
    projectType: 'residential',
    systemSize: '10.0',
    totalCost: '32500.00',
    costPerWatt: '3.25',
    installationDate: '2023-09-10',
    communicationRating: 5,
    timelinessRating: 5,
    qualityRating: 5,
    valueRating: 5,
    isVerified: true,
    isPublished: true,
    createdAt: '2023-10-01',
    updatedAt: '2023-10-01'
  }
]
